### ISSUE TITLE
Calls to Ruff format/check fail on Windows for large document sets

### ISSUE THREAD

**Issue by SrirachaHorse** [tefra/xsdata#1048]
For sufficiently large XSD schemas that are split into multiple schemas or documents, this often produces a large number of corresponding dataclass files, in particular if using configuration options such as `namespace-clusters`. In such cases, `DataclassGenerator.ruff_code()` will be called on all of these files at once.

On Windows there is a character limit on CLI commands of approximately 32k. If this limit is exceeded by attempting to pass a large number of files to Ruff via `subprocess.run()`, this will produce a Windows error and fail when generating dataclasses:

```
FileNotFoundError: [WinError 206] The filename or extension is too long
```

None of the input filenames individually exceed the Windows MAX_PATH limit, so this is an issue with the number of files attempting to be processed at once, rather than an issue with a particular file.

The regression appears to be a result of #1043, as that was the change that introduced the "all files at once" approach instead of running Ruff on each file separately.

**Comment by tefra** [comment]
One step forward, two steps back 🤦 

The reason I went with the specific filenames is because people often, they add user stuff in the output folder, which isn't a great practise in my opinion. 

The first option with the batches could work for everyone, but it would tricky to test. I am wondering if we should go the hard way and run ruff on the output package, add a warning in the docs to prohibit people from adding code in the output package and be done with it.
