### ISSUE TITLE
Confusing generation of py files with multiple directories and complicated imports

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#164]
This one's tricky to describe: run `xsdata --package hl7 coreschemas/ multicacheschemas/` in the common types HL7v3 directory. You will see some `py` files generated in `hl7` and some in `coreschemas`. I'd expect it to be done all in `hl7` or a subdirectory thereof.

**Comment by tefra** [comment]
I see an issue here

for example 
`coreschemas/infrastructureRoot.xsd`  has the following import

```
<xs:include schemaLocation="../coreschemas/voc.xsd"/>
```

the following would be enough, but still the cli should clear these cases I am on it!

```
<xs:include schemaLocation="voc.xsd"/>
```


I also see another issue on how you use the cli, `multicacheschemas/` already includes through imports the schemas from `coreschemas/` I would suggest to only use one directory as your base.

Also xsdata follows the paths of the files in order to generate the packages if you know one of your schemas is doing an import from a parent directory you need to adjust the target package on your own.

I thought in the begging I could make the cli to do that adjustment but then I had this stupid case and gave up. 

```
a.xsd -> imports common/b.xsd --> ../../common/b.xsd
```


so I would suggest to run it like this for more sane results

```
xsdata --package hl7.multicacheschemas multicacheschemas/
```

**Comment by tefra** [comment]
Actually I take that back the cli actually works quite well of the explicit relative paths if you adjust the initial package, let me know @nimish if you think there is something more to this issue

**Comment by nimish** [comment]
@tefra yeah i think that workaround makes sense. I do think it's a little surprising so maybe a warning or something could be generated, but being more explicit about packages works fine for me

**Comment by tefra** [comment]
the next release will take care of this issue, you won't have to adjust the package name on your own the cli will detect the the common path of the sources and put everything inside the package as you defined, I think this behavior as you suggested is more acceptable.

So running it like this will produce the same output for you automatically.

 `xsdata --package hl7 multicacheschemas/`
