### ISSUE TITLE
textual values of boolean type

### ISSUE THREAD

**Issue by gjvc** [tefra/xsdata#232]
Having updated from version 20.7 to 20.8 (actually master 143cdefc4e22099c12d33e8a2adf1033d56b4178 since taking on the fix from #230) I'm getting the following messages when i run my application.  These messages did not appear when using 20.7.

```
/home/gjvc/projects/INVENTORY/explorer/server/.venv/lib/python3.8/site-packages/xsdata/formats/converters.py:46: ConverterWarning: Failed to convert value `FALSE` to one of [<class 'bool'>]
  warnings.warn(
/home/gjvc/projects/INVENTORY/explorer/server/.venv/lib/python3.8/site-packages/xsdata/formats/converters.py:46: ConverterWarning: Failed to convert value `TRUE` to one of [<class 'bool'>]
  warnings.warn(
```

What should I be doing here?  I need to be able to read and write the boolean values from an attribute like this 

```
<feature behaviour1="true" behaviour2="FALSE" behaviour3="yes" behaviour4="NO" />
```

I suggest that xsdata should be able to read, case-insensitively, both true/false and yes/no textual values for boolean values, and generate true/false (lower-case) as textual values for boolean values.

**Comment by tefra** [comment]
When the converter fails to convert a value to a primitive type like `bool` it falls back to a simple string and practically violates the model field type :sweat_smile:

That's the default behavior since the beginning,  the warnings were added in v20.8 so unknown cases can be reported and fixed. So nothing really has changed, but if these warnings are blocking you in any way, you can always [suppress them]( https://docs.python.org/3/library/warnings.html#overriding-the-default-filter).

Anyway on topic, according to the specification the xs:boolean type accepts only one of these `{true, false, 1, 0}` values , anything else is invalid. https://www.w3.org/TR/xmlschema-2/#boolean

Although I am not so sure it's the right decision, I could make the converter from xml to python to be more lenient to actually normalize these cases, but again if we are also talking about the opposite from python to xml then it's impossible since the original non-standard representation (NO, YES, True, False) is not defined anywhere, in that case I am afraid your only option is to modify the schema to change the types for those elements/attributes from `xs:boolean` to `xs:string`

I am guessing these xml documents are manually modified and are not generated by a library right?

**Comment by tefra** [comment]
Even if I made the parsing of boolean more lenient, valid cases where a field can be a union of both bool and str would break, well not break but the output xml document wont match the input document.


### From the w3c test suite

```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="union">
		<xsd:union memberTypes="xsd:boolean xsd:int xsd:string"/>
	</xsd:simpleType>
	<xsd:element name="root">
		<xsd:simpleType>
			<xsd:list itemType="union"/>
		</xsd:simpleType>
	</xsd:element>
</xsd:schema>
```

```python
@dataclass
class Root:
    """
    :ivar value:
    """
    class Meta:
        name = "root"

    value: List[Union[bool, int, str]] = field(
        default_factory=list,
        metadata=dict(
            tokens=True
        )
    )
```

### **input** 

```xml 
<root>1 true abcdef false 10000 NO</root>
```

### **output**

```xml 
<root>1 true abcdef false 10000 false</root>
```

**Comment by gjvc** [comment]
_xs:boolean type accepts only one of these {true, false, 1, 0}_

I'll take the official specification as the law and normalize the XML upon reading it to conform. ( I have had to include this normalization layer in any event, because of clashes between tag names, completely separate to this issue.)

Please close this item as a non-issue.  I was thrown slightly by the appearance of the warnings, but they are nothing materially new, as you say.  I'll leave the warnings unsuppressed to catch any failed conversions. (there have been cases where someone has typed "fasle" in the attribute value....)

**Comment by tefra** [comment]
I closed this but I will revisit the issue of being able to register custom converters to handle this kind of situations.
