### ISSUE TITLE
List[object] when generating classes for European Datex2 schema

### ISSUE THREAD

**Issue by eLvErDe** [tefra/xsdata#371]
Hello,

I think, there might be something wrong because I'm pretty sure it expects some precise types ;-)

```
xsdata generate https://docs.datex2.eu/_static/data/v3.1/DATEXII_3_Situation.xsd --output pydata
```

Now checks class LocationReference: aroung line 1179:

```python
@dataclass
class LocationReference:
    """Represents one or more physically separate locations. Multiple locations may
    be related, as in an itinerary or route, or may be unrelated. One
    LocationReference should not use multiple Location objects to represent the
    same physical location.

    :ivar location_reference_extension:
    """
    location_reference_extension: Optional[TypeExtensionType] = field(
        default=None,
        metadata={
            "name": "_locationReferenceExtension",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/3/locationReferencing",
        }
    )
```

Class TypeExtensionType (well, the name even sounds like there's already something wrong) is defined like this:

```python
@dataclass
class TypeExtensionType:
    """
    :ivar any_element:
    """
    class Meta:
        name = "_ExtensionType"

    any_element: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        }
    )
```

Any idea ? Thanks a lot in advance and happy new year !

**Comment by tefra** [comment]
Hi @eLvErDe 

https://docs.datex2.eu/_static/data/v3.1/DATEXII_3_Situation.xsd

```xml
<xs:element name="locationReference" type="loc:LocationReference"/>
```

https://docs.datex2.eu/_static/data/v3.1/DATEXII_3_LocationReferencing.xsd

```xml
<xs:complexType name="LocationReference" abstract="true">
        ....
	<xs:sequence>
		<xs:element name="_locationReferenceExtension" type="com:_ExtensionType" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>
```

https://docs.datex2.eu/_static/data/v3.1/DATEXII_3_Common.xsd

```xml
<xs:complexType name="_ExtensionType">
	<xs:sequence>
		<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>
```

The generator is trying to flatten the models as much as possible, that's why it has merged the element and the first complexType together, if that's what you mean. Other than that `any` elements act like wildcards that can accept any content.

The parser on the fly will try to match unknown xml nodes to one of the other defined models if possible otherwise it will use a generic [model](https://github.com/tefra/xsdata/blob/master/xsdata/formats/dataclass/models/generics.py#L15)

The output names look funny because of the original underscores, the name sanitizer is adding a safe prefix, that part could be improved...

**Comment by eLvErDe** [comment]
Thanks for the quick reply :)

So for you the model actually allow a list off "any", that's.. weird (from a functional perspective).

I'll give a try with java jaxb tomorrow, just to be sure

**Comment by tefra** [comment]
xsdata is actually inspired from jaxb and I often use it to compare generated models and fields. xjc actually fails to run on your whole definition because of duplicate class names, it needs some customization to resolve those, but for our excerpt this is the generated code.

```java
public abstract class LocationReference {

    @XmlElement(name = "_locationReferenceExtension")
    protected ExtensionType locationReferenceExtension;
```

```java
public class ExtensionType {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
```

The scope of wildcards is to have extensible schemas, but yeah sometimes it can become messy.

**Comment by tefra** [comment]
Let me know if you have any suggestions to improve xsdata's behavior with wildcards

**Comment by eLvErDe** [comment]
Hello @tefra 

Actually, I'm pretty sure there's something wrong here, generated XML looks like:

```
        <ns0:locationReference xmlns:ns0="http://datex2.eu/schema/3/situation" xmlns:ns1="http://datex2.eu/schema/3/locationReferencing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns1:Location">
                <ns1:_locationReferenceExtension>
                        <ns1:SingleRoadLinearLocation>
                                <ns1:gmlLineString srsDimension="2" srsName="EPSG:4326">
```

And I'm sure this <_locationReferenceExtension> element should not be there...

Regards, Adam.

**Comment by tefra** [comment]
This is the complexType referenced by the xsi:type

```
  <xs:complexType name="Location" abstract="true">
    ...
    <xs:complexContent>
      <xs:extension base="loc:LocationReference">
        ....
      </xs:extension>
    </xs:complexContent>
  
```

```
  <xs:complexType name="LocationReference" abstract="true">
    ...
    <xs:sequence>
      <xs:element name="_locationReferenceExtension" type="com:_ExtensionType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
```

Please open a new issue and provide some samples as well that would help a lot to identify the issue(s) here
