### ISSUE TITLE
Using restrictions in the XSD to reduce overhead

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#490]
Several restrictions within an XSD such as min and max value may reduce the required datatype to store this value. In addition it will directly cause an issue if the value is exceeded. Would this be a direction you want to make the code generator aware of these restrictions to go _beyond_ types?

**Comment by tefra** [comment]
xsdata is not meant to be a validation tool and from time to time I debate why am I adding them to the generated models but yeah the vision is to create validators based on these restrictions, but patterns especially scare me.

What do you mean about reducing overhead like using different datatypes?

**Comment by skinkie** [comment]
> What do you mean about reducing overhead like using different datatypes?

Imagine would have an xs:int, but only allow the values 1, 100. Why not make the datatype a byte or even a _boolean_?

**Comment by tefra** [comment]
python doesn't have the builtin datatypes to map stuff like xs:int, xs:short, xs:long: xs:integer, xs:positiveInteger to specific datatypes, that's why everything is mapped to `int`.

Now mapping stuff like xs:int with max/min (inclusive) 0,1 to boolean isn't a very good practice either, for once the roundtrip conversions wouldn't work.
