### ISSUE TITLE
Many base64 embedded images within XML break parsing

### ISSUE THREAD

**Issue by pashashocky** [tefra/xsdata#610]
Heya, I have some documents where there have been quite a few base64 embedded images embedded in the html structure of an XML field.

For example: `<img src="data:image/png;base64,......`

Having more than some amount actually ends up breaking the parser it seems, the output of `parser.from_string(xml, Article)` ends up being the value of the previous element, no exception is being raised right now.

**Comment by tefra** [comment]
can you provide with some samples and modes?

**Comment by pashashocky** [comment]
Yessir, I've made a simple example that breaks, based on the altered version of books from tests.
You can get it from my Dropbox [here](https://www.dropbox.com/s/mvj4yydjdh7fpu0/ex_b64_breaks_parser.zip?dl=0). 
Please, let me know if any questions. Thank you @tefra!

**Comment by tefra** [comment]
This is very tricky

1. the lxml handler has a limit of characters per text nodes and is throwing an exception 
` xmlSAX2Characters: huge text node, line 126929, column 25 (bk001.xml, line 126929)`

2. For max compatibility xsdata is using lxml with **recover** mode on

https://github.com/tefra/xsdata/blob/1cd681598d2235626d0e21716fc9fb885d26e351/xsdata/formats/dataclass/parsers/handlers/lxml.py#L45

Unfortunately the recover mode is hiding the exception, xsdata should have raised an error since the result is not the requested type. :facepalm: 

As a quick alternative solution please use the native python xml handler, it works just fine.

```python
from book import BookForm
from pathlib import Path
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.parsers.handlers import XmlEventHandler

config = ParserConfig(
    fail_on_unknown_properties=True,
    fail_on_unknown_attributes=True,
    fail_on_converter_warnings=True,
)
parser = XmlParser(config=config, handler=XmlEventHandler)
ex = parser.from_path(Path('b64issue/bk001.xml'), BookForm)
```

I will try to detect such issues and raise a proper exception...

Thanks for reporting @pashashocky

**Comment by pashashocky** [comment]
Thank you @tefra, 

I think the best UX solution would be for xsdata to parse these with the Python Xml handler once the issue is detected in the lxml handler and give the user the option to raise warnings about having to do that as an option to the parser.

**Comment by tefra** [comment]
Closing for now
