### ISSUE TITLE
restriction base not used in generation

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#738]
I am currently using analysis on mro basis in order to figure out how objects relate to eachother.

I notice that "restriction base" is not affecting the schema generation. Below are some examples. Can the restriction base used for inheritance. Or am I missing the point of the restriction in the first place?

https://github.com/NeTEx-CEN/NeTEx/issues/407#issuecomment-1398257962

**Comment by tefra** [comment]
Usually the base classes are not flattened unless, there is a reason, I am gonna take a look and see what's the issue with these restriction bases

**Comment by tefra** [comment]
Early on, xsdata couldn't handle type overrides very good, so whenever a subclass was overriding a parent class field and the types didn't match the base classes were flattened. That part of the code is no longer relevant and actually had a few major flaws.

After I removed the faulty code, a few more issues came up and I had to harden a few things in compound fields. As always the netex schemas keep on giving some excellent use cases :rocket: 

Thank you @skinkie for the report, the fix is on master, give it a try and let me know what you think.

**Comment by skinkie** [comment]
@tefra will try! :-)

**Comment by tefra** [comment]
The output for netex suite just got ~20k lines of codes smaller

https://github.com/tefra/xsdata-samples/commit/8e02a9da5ad2ce94cbcff4738236d70e1b4b5eb2

**Comment by skinkie** [comment]
Let's hope that my mro analyzer still works ;-)
